# Generated by Django 3.1.6 on 2021-05-10 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210510_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 10, 11, 40, 30, 520965, tzinfo=utc)),
        ),
    ]
